### ISSUE TITLE
[compat2021] Make browser version changes visible

### ISSUE THREAD

**Issue by stephenmcgruer** [Ecosystem-Infra/wpt-results-analysis#34]
It is currently difficult to tell what change caused an increase (or decrease!) in pass-rate of a given browser at a given point in time. This could be due to new tests being added, or a change in the browser itself, or ...

To help with this, we should make the browser version visible in some way - either on the individual data points or via annotations.

**Comment by chrishtr** [comment]
Also browser minor version?

**Comment by stephenmcgruer** [comment]
Heh, I wondered how long it would be before someone asked about that. I didn't expect day zero ;).

I cut it for length (https://github.com/Ecosystem-Infra/wpt-results-analysis/commit/2d8fd879b6c31877efb6ce999a68197f663fadd3#diff-f761a80ddbb7262f001c8ba11e484ddc5b33857acc288d5243046b0ab81efc50R128), because the Chromium ones were very long (`83.0.12345.1`); when you say minor version do you just want `83.0` or is the full version important to you here?

**Comment by chrishtr** [comment]
I think we need the full number. That will allow easier bisects. While I have your attention: is it feasible to, on click, make the tooltip stick on the page, and put a link in it with a revision bisect from the last version? Just the click stickiness change would help because otherwise you can't move the mouse without losing it.

**Comment by stephenmcgruer** [comment]
> I think we need the full number.

Done.

> While I have your attention: is it feasible to, on click, make the tooltip stick on the page, and put a link in it with a revision bisect from the last version? Just the click stickiness change would help because otherwise you can't move the mouse without losing it.

TBD, though we can certainly do something to this effect. What bisect link(s) are you thinking of though; can you give examples for each browser?

**Comment by stephenmcgruer** [comment]
> on click, make the tooltip stick on the page

Done. So just the 'what is a bisect link' now :)

**Comment by chrishtr** [comment]
Chromium: https://chromium.googlesource.com/chromium/src/+log/90.0.4421.0..90.0.4427.0?pretty=fuller&n=10000

Looking for other browsers, but we could start with that?

**Comment by stephenmcgruer** [comment]
> Looking for other browsers, but we could start with that?

Added for Chrome. Unfortunately the support for this in Google Charts turned out to be a little janky, so the button shows up for all browsers even though its only supported on Chrome :(. Hopefully we can find revision links for the other two so that it makes more sense!

**Comment by chrishtr** [comment]
I sent an email to Mozilla asking how.

For Webkit, Ali Juma said that as far as he knows there is no automated way to generate a link. There is a link, but it's embedded in the webkit blog post for each Developer Preview release. I suggest we link to another wpt.fyi page (e.g. wpt.fyi/safari-developer-preview-diff?N=120 that says the following:

"You're looking for the diff from SAFari Developer Preview N-1 to N. To do this, go to the [webkit blog](https://webkit.org/blog/) and find the version N release post. In it you'll find a link to a diff from version N-1. [Here is an example post](https://webkit.org/blog/11548/release-notes-for-safari-technology-preview-120/), and [here](https://trac.webkit.org/log/webkit/?stop_rev=271358&rev=271794&limit=999) is the link in that post to the diff."

(Where N would be auto-filled from a query parameter

**Comment by chrishtr** [comment]
Mozilla:

https://hg.mozilla.org/mozilla-unified/pushloghtml?fromchange=FIREFOX_85_0_1_RELEASE&tochange=FIREFOX_86_0_RELEASE

**Comment by chrishtr** [comment]
List of all tags: https://hg.mozilla.org/mozilla-unified/tags

**Comment by stephenmcgruer** [comment]
Unfortunately for Firefox we use Nightly builds, and those are unversioned outside of major version number (i.e. they're all called `87.0a1`, even when that represents dozens of builds over time). We could switch to beta builds, if Mozilla are ok with that ([wpt.fyi diff isn't too big](https://wpt.fyi/results/?diff&filter=ADC&run_id=5642715209400320&run_id=5765918695096320), but I need to verify what the score/graph change would actually be). Otherwise I can start to dig into whether pushlog supports dated diffs, which probably also works for Nightly because they get built twice daily.

**Comment by sylvestre** [comment]
We have tags for nightly builds here: 
https://hg.mozilla.org/mozilla-central/firefoxreleases
I am not sure you can leverage this for your links?

Maybe moving to beta for Firefox will be easier.

**Comment by stephenmcgruer** [comment]
Thanks @sylvestre for the input! I ended up launching a flow that prompts the user to look up the revisions manually (at that URL) and then we can auto-generate a URL from that if they want.

![image](https://user-images.githubusercontent.com/153264/112665234-36458700-8e31-11eb-9d6b-fd0868dbd6e0.png)
