### ISSUE TITLE
[compat2021] put it on wpt.fyi

### ISSUE THREAD

**Issue by foolip** [Ecosystem-Infra/wpt-results-analysis#36]
After discussing options with @chrishtr we think that hosting this on wpt.fyi/compat2021 would make the most sense.

**Comment by foolip** [comment]
Making this somewhat prominent to users of wpt.fyi would also be great. In https://github.com/web-platform-tests/wpt.fyi/issues/1519 we discussed having a landing page for wpt.fyi, and if we did I think this would be perfect material for something to highlight, in addition to the "just show me results" and "just show me some BSF graphs" options.

**Comment by foolip** [comment]
Here's a silly mockup of what it could look like:
![image](https://user-images.githubusercontent.com/498917/109232139-1d14d080-77c8-11eb-9634-628793bb58df.png)

**Comment by stephenmcgruer** [comment]
Et voila: https://wpt.fyi/compat2021

The only thing left to do for this issue is make https://ecosystem-infra.github.io/wpt-results-analysis/compat redirect to that I think.

**Comment by foolip** [comment]
✨Yay!✨
