### ISSUE TITLE
[compat2021] The Stable/Nightly option should rather be a toggle

### ISSUE THREAD

**Issue by robnyman** [Ecosystem-Infra/wpt-results-analysis#39]
The Stable/Nightly option should rather be a toggle, I think, so it's clear what the current one is and how to switch. People I've shown it to misses the Stable releases checkbox text.

**Comment by foolip** [comment]
Suggested in https://github.com/web-platform-tests/wpt.fyi/pull/2472#pullrequestreview-610761771
