### ISSUE TITLE
[compat2021] Rename page title to Compat 2021 / similar

### ISSUE THREAD

**Issue by robnyman** [Ecosystem-Infra/wpt-results-analysis#40]
We should rename it to "Compat 2021", "#Compat2021" or similar for consistency between messages and channels.

**Comment by foolip** [comment]
Suggested in https://github.com/web-platform-tests/wpt.fyi/pull/2443#pullrequestreview-610751715

**Comment by stephenmcgruer** [comment]
Fixed in the version we're pushing to wpt.fyi, so closing. See https://staging.wpt.fyi/compat2021
