### ISSUE TITLE
[compat2021] Enabling easy iframing of the dashboard

### ISSUE THREAD

**Issue by robnyman** [Ecosystem-Infra/wpt-results-analysis#41]
There will be places to iframe the dashboard in, like web.dev and MDN Insights. However, for those places, having complete bug lists would be overwhelming. While that can be addressed with iframe height and no scrolling, it would be nice – if possible – to just pass in parameters in the querystring.

E.g. `wpt.fyi/compat2021?nobugs=1`, `wpt.fyi/compat2021?notitle=1`

**Comment by stephenmcgruer** [comment]
https://github.com/web-platform-tests/wpt.fyi/pull/2484 adds an embedded mode that hides the header (https://staging.wpt.fyi/compat2021?embedded). The test results view isn't added back yet, so I'm going to close this and leave a note on https://github.com/web-platform-tests/wpt.fyi/issues/2482
