### ISSUE TITLE
[compat2021] Show summary scores over time as default graph view

### ISSUE THREAD

**Issue by robnyman** [Ecosystem-Infra/wpt-results-analysis#43]
I feel that if you come in now, there's a paragraph of text and you need to explicitly choose a Focus area. I think it would be better to have one area preselected and get people excited about, and aware of, the presence of graphs.

**Comment by stephenmcgruer** [comment]
From discussion offline, I believe we have agreed on the default view being all features (i.e. the overall score) instead. This will require some backend changes to accomplish but shouldn't be too hard (he says).

**Comment by stephenmcgruer** [comment]
This is now done.
